/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.tottokug.workflow;

import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClientExternal;

/**
 * Generated from {@link com.tottokug.workflow.SampleWorkflow}. 
 * Used to start workflow executions or send signals from outside of the scope of a workflow.
 * Created through {@link SampleWorkflowClientExternalFactory#getClient}.
 * <p>
 * When starting child workflow from a parent workflow use {@link SampleWorkflowClient} instead.
 */
public interface SampleWorkflowClientExternal extends WorkflowClientExternal
{

    /**
     * Generated from {@link com.tottokug.workflow.SampleWorkflow#workflow}
     */
    void workflow();

    /**
     * Generated from {@link com.tottokug.workflow.SampleWorkflow#workflow}
     */
    void workflow(StartWorkflowOptions optionsOverride);
}