/*
 * This code was generated by AWS Flow Framework Annotation Processor.
 * Refer to Amazon Simple Workflow Service documentation at http://aws.amazon.com/documentation/swf 
 *
 * Any changes made directly to this file will be lost when 
 * the code is regenerated.
 */
 package com.tottokug.workflow;

import com.amazonaws.services.simpleworkflow.flow.core.Promise;
import com.amazonaws.services.simpleworkflow.flow.StartWorkflowOptions;
import com.amazonaws.services.simpleworkflow.flow.WorkflowClient;

/**
 * Generated from {@link com.tottokug.workflow.SampleWorkflow}. 
 * Used to invoke child workflows asynchronously from parent workflow code.
 * Created through {@link SampleWorkflowClientFactory#getClient}.
 * <p>
 * When running outside of the scope of a workflow use {@link SampleWorkflowClientExternal} instead.
 */
public interface SampleWorkflowClient extends WorkflowClient
{

    /**
     * Generated from {@link com.tottokug.workflow.SampleWorkflow#workflow}
     */
    Promise<Void> workflow();

    /**
     * Generated from {@link com.tottokug.workflow.SampleWorkflow#workflow}
     */
    Promise<Void> workflow(Promise<?>... waitFor);

    /**
     * Generated from {@link com.tottokug.workflow.SampleWorkflow#workflow}
     */
    Promise<Void> workflow(StartWorkflowOptions optionsOverride, Promise<?>... waitFor);

}